# Generated by Django 3.0.7 on 2020-06-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsweek', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsweek',
            name='Issn',
        ),
        migrations.RemoveField(
            model_name='newsweek',
            name='Title2',
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='Title1',
            field=models.TextField(),
        ),
    ]
