# Generated by Django 3.0.7 on 2020-06-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsweek', '0005_newsweek_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsweek',
            name='Points',
            field=models.IntegerField(default=1),
        ),
    ]
