# Generated by Django 3.0.7 on 2020-07-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsweek', '0008_auto_20200716_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsweek',
            name='Second Title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='Title',
            field=models.CharField(max_length=250),
        ),
    ]
