# Generated by Django 3.0.7 on 2020-07-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsweek', '0009_auto_20200716_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsweek',
            name='automatic, electronic and electrotechnic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsweek',
            name='chemical engineering',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsweek',
            name='civil engineering and transport',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsweek',
            name='environmnetal engineering, mining and energetic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsweek',
            name='linguistics',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsweek',
            name='literature',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsweek',
            name='material engineering',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsweek',
            name='mechanical engineering',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsweek',
            name='medical sciences',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsweek',
            name='pharmaceutical sciences',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsweek',
            name='studies on arts',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsweek',
            name='studies on culture and religion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsweek',
            name='technical IT and telecomunication',
            field=models.TextField(null=True),
        ),
    ]
