# Generated by Django 3.0.7 on 2020-07-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsweek', '0010_auto_20200720_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsweek',
            name='architecture and urbanistic',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
