# Generated by Django 3.0.7 on 2020-07-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsweek', '0011_auto_20200720_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsweek',
            name='architecture and urbanistic',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='automatic, electronic and electrotechnic',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='chemical engineering',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='civil engineering and transport',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='environmnetal engineering, mining and energetic',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='history',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='linguistics',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='literature',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='material engineering',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='mechanical engineering',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='medical sciences',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='pharmaceutical sciences',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='studies on arts',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='studies on culture and religion',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='technical IT and telecomunication',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
