# Generated by Django 3.0.7 on 2020-07-20 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsweek', '0012_auto_20200720_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsweek',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='newsweek',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
