# Generated by Django 3.0.7 on 2020-07-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsweek', '0014_auto_20200720_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsweek',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='newsweek',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
