# Generated by Django 3.0.7 on 2020-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsweek', '0015_auto_20200720_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsweek',
            name='architecture and urbanistic',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
