# Generated by Django 3.0.7 on 2020-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsweek', '0016_auto_20200720_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsweek',
            name='studies on culture and religion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
