# Generated by Django 3.0.7 on 2020-09-23 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsweek', '0018_auto_20200720_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsweek',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
