# Generated by Django 3.0.7 on 2020-09-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsweek', '0021_auto_20200923_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsweek',
            old_name='author',
            new_name='authorus',
        ),
    ]
