# Generated by Django 3.0.7 on 2020-09-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsweek', '0022_auto_20200929_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsweek',
            old_name='authorus',
            new_name='author',
        ),
    ]
